site: AyBorg

url: https://ayborg.io
baseurl: 

languages: ["en", "de"]
defaultLang: en
languageNames:
  en: English
  de: Deutsch
default_locale_in_subfolder: false

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
    type: "post"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "*/docs"
      type: "pages"
    values:
      layout: "docs"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

paginate: 6
paginate_path: "/blog/page:num/"
  
