namespace AyBorg.Plugins.ZXing.Models
{
        public enum BarcodeFormats
        {
                All,
                All_1D,
                All_2D,
                AZTEC,
                CODABAR,
                CODE_39,
                CODE_93,
                CODE_128,
                DATA_MATRIX,
                EAN_8,
                EAN_13,
                ITF,
                MAXICODE,
                PDF_417,
                QR_CODE,
                RSS_14,
                RSS_EXPANDED,
                UPC_A,
                UPC_E,
                UPC_EAN_EXTENSION,
                MSI,
                PLESSEY,
                IMB,
                PHARMA_CODE
        }
}
