name: BuildSelfContained

inputs:
  service:
    required: true
  artifact:
    required: true

runs:
  using: "composite"
  steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: Restore dependencies
          shell: bash
          run: dotnet restore
        - name: Publish (osx-arm64)
          shell: bash
          working-directory: src/${{ inputs.service }}
          run: dotnet publish -c release -r osx-arm64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ../../build/osx-arm64
        - name: Publish (linux-x64)
          shell: bash
          working-directory: src/${{ inputs.service }}
          run: dotnet publish -c release -r linux-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ../../build/linux-x64
        - name: Publish (win-x64)
          shell: bash
          working-directory: src/${{ inputs.service }}
          run: dotnet publish -c release -r win-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ../../build/win-x64
        - name: Copy license
          shell: bash
          run: cp LICENSE build/osx-arm64 && cp LICENSE build/linux-x64 && cp LICENSE build/win-x64
        - name: Upload artifacts
          uses: actions/upload-artifact@v3
          with:
            name: ${{ inputs.artifact }}
            path: build
