name: BuildSelfContained

inputs:
  service:
    required: true
  artifact:
    required: true
  runtime:
    required: true

runs:
  using: "composite"
  steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: Restore dependencies
          shell: bash
          run: dotnet restore
        - name: Publish
          shell: bash
          working-directory: src/${{ inputs.service }}
          run: dotnet publish -c release -r ${{ inputs.runtime }} --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=embedded -o ../../build/${{ inputs.runtime }}
        - name: Copy license
          shell: bash
          run: cp LICENSE build/${{ inputs.runtime }}
        - name: Delete appsettings.Development.json
          shell: bash
          run: rm build/${{ inputs.runtime }}/appsettings.Development.json
        - name: Upload artifacts
          uses: actions/upload-artifact@v3
          with:
            name: ${{ inputs.artifact }}
            path: build
            retention-days: 2
