name: Publish Release

inputs:
  service:
    required: true
  artifact:
    required: true

runs:
  using: "composite"
  steps:
    - name: Zip ${{ inputs.service }}
      uses: vimtor/action-zip@v1.1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/${{ inputs.artifact }}
        dest: AyBorg.${{ inputs.service }}.zip
    - name: Publish ${{ inputs.service }}
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: AyBorg.${{ inputs.service }}.zip
